### ISSUE TITLE
Arduino Uno Post using TI CC3000 WiFi board

### ISSUE THREAD

**Issue by RaceRon** [attm2x/m2x-arduino#4]
It appears that this function doesn't work reliably any more. The code hangs up waiting for response from AT&T server. Same program use to work great before!!

**Comment by xxuejie** [comment]
Sorry for the delay and the trouble caused! This seems to be working at my end, could you be more specific on the problem? For example, the following parts might help us know better on the problem:

1. What API endpoint are you using? Any change you can strip the code down to only the API part if the rest of the code can't be shared?
2. What version of M2X are you using? Are you downloading one of our releases or the master branch? Checking [here](https://github.com/attm2x/m2x-arduino/blob/master/M2XStreamClient/M2XStreamClient.h#L11) will help you know what version you are using.

**Comment by RaceRon** [comment]
I have attached the part  of the sketch where it hangs up 95% of the time, occasionally it works and I get the correct response back. As I have stated before this sketch would run for 2-3 days before having problems. The problems started about two months ago. I use the entire sketch to monitor  my water well pumping status. The complete sketch records my pump status ( ON or OFF) as well as saving a random number every ten minutes to let me know the program is running or has halted. I have included the part that records a “0” to the Pump stream name as well as saving the random number to another variable named “Still_Alive”

I have the latest version of M2X Clients, and I know I have the correct API’s because I can look at the Log file on the M2X webpage see below. I don’t know where all the “GET” messages are coming from?? I believe that is the problem!!

 

Thanks

 

API Request Log History


STATUS

REQUEST

TIMESTAMP


200

GET /devices/2ea7f37d0cf4dd6ab54d293ecf54b3aa/streams/PumpOn/values

09/08/2015 23:57:40.667 UTC


200

GET /devices/2ea7f37d0cf4dd6ab54d293ecf54b3aa/streams/Still_Alive/stats

09/08/2015 23:57:24.685 UTC


200

GET /devices/2ea7f37d0cf4dd6ab54d293ecf54b3aa/streams/PumpOn/stats

09/08/2015 23:57:24.615 UTC


200

GET /devices/2ea7f37d0cf4dd6ab54d293ecf54b3aa/triggers/

09/08/2015 23:57:23.972 UTC


200

GET /devices/2ea7f37d0cf4dd6ab54d293ecf54b3aa/streams/

09/08/2015 23:57:23.915 UTC


200

GET /devices/2ea7f37d0cf4dd6ab54d293ecf54b3aa/streams/PumpOn/values

09/03/2015 20:44:28.366 UTC


200

GET /devices/2ea7f37d0cf4dd6ab54d293ecf54b3aa/streams/PumpOn/stats

09/03/2015 20:44:20.353 UTC


200

GET /devices/2ea7f37d0cf4dd6ab54d293ecf54b3aa/streams/Still_Alive/stats

09/03/2015 20:44:20.352 UTC


200

GET /devices/2ea7f37d0cf4dd6ab54d293ecf54b3aa/triggers/

09/03/2015 20:44:19.839 UTC


200

GET /devices/2ea7f37d0cf4dd6ab54d293ecf54b3aa/streams/

09/03/2015 20:44:19.747 UTC


202

PUT /devices/2ea7f37d0cf4dd6ab54d293ecf54b3aa/streams/Still_Alive/value

09/03/2015 20:16:10.994 UTC


202

PUT /devices/2ea7f37d0cf4dd6ab54d293ecf54b3aa/streams/PumpOn/value

**Comment by xxuejie** [comment]
@RaceRon Thanks for your reply! We are checking both the client and the server logs to see where might go wrong in our code. We will let you know once we have something to share.

To answer your questions: those requests are generated while you are accessing M2X website through a browser. So no worries on them :)

**Comment by RaceRon** [comment]
Any update to this?

 

Thanks

**Comment by xxuejie** [comment]
@RaceRon We do have look into this from both the client side and the server side, unfortunately we found nothing wrong here. We will continue to look into the agent code, but we do appreciate it if you can also check it at your side. Do you think if this is possible?

**Comment by kristinpeterson** [comment]
@aldoagosta hello! Could you please [submit a ticket](https://developer.att.com/support/submit-a-ticket) and our support team will help you out?
