### ISSUE TITLE
Add Post Device Update (Single Values to Multiple Streams)

### ISSUE THREAD

**Issue by kristinpeterson** [attm2x/m2x-arduino#5]
Add [Post Device Update (Single Values to Multiple Streams)](https://m2x.att.com/developer/documentation/v2/device#Post-Device-Update--Single-Values-to-Multiple-Streams-) endpoint to the following client libraries, method should be named `postDeviceUpdate`

**Comment by xxuejie** [comment]
Done by https://github.com/attm2x/m2x-arduino/commit/296dedb17013f40626188bdb1b7672023a21afac
