### ISSUE TITLE
Add Support for Commands API


### ISSUE THREAD

**Issue by kristinpeterson** [attm2x/m2x-arduino#6]
Add support for the [Commands API](https://m2x.att.com/developer/documentation/v2/commands).

Per the [Limited Client Contribution Guidelines](https://github.com/attm2x/m2x-service/blob/master/LIMITED-CLIENT-CONTRIBUTIONS.md#supported-api-methods) only the following endpoints need to be supported for limited clients:

  - [`GET /devices/:id/commands`](https://m2x.att.com/developer/documentation/v2/commands#Device-s-List-of-Received-Commands)
  - [`PUT / devices/:id/commands/:id/process`](https://m2x.att.com/developer/documentation/v2/commands#Device-Marks-a-Command-as-Processed)
  - [`PUT /devices/:id/commands/:id/reject`](https://m2x.att.com/developer/documentation/v2/commands#Device-Marks-a-Command-as-Rejected)

**Comment by xxuejie** [comment]
This is now finished

**Comment by kristinpeterson** [comment]
:smile_cat:
